import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  //Tst generado por el codegen de playwright, para probar la funcionalidad de descarga de un archivo, y luego se agrego una pausa para ver el proceso de descarga.
  await page.goto('https://sellercenter.ripleyqa.com/login');
  await page.locator('div').filter({ hasText: /^ContraseñaContraseña$/ }).first().click();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('qa-testing-cl');
  await page.getByRole('textbox', { name: 'Nombre de usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de usuario' }).click();
  await page.getByRole('textbox', { name: 'Nombre de usuario' }).fill('qa-testing-cl');
  await page.getByRole('textbox', { name: 'Contraseña' }).dblclick();
  await page.getByRole('textbox', { name: 'Contraseña' }).fill('98FU8C');
  await page.getByTestId('login-form-button').click();
  await page.getByRole('button', { name: 'Productos y precios' }).click();
  await page.getByRole('button', { name: 'Historial de carga' }).click();
  await page.getByRole('combobox', { name: '25' }).click();
  await page.getByRole('option', { name: '50' }).click();
  await page.getByRole('combobox', { name: '50' }).press('PageDown');
  await page.getByRole('combobox', { name: '50' }).press('PageUp');
  await page.getByRole('combobox', { name: '50' }).press('PageUp');
  await page.locator('div').filter({ hasText: 'Historial de cargaEn esta' }).nth(1).click();
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByRole('cell', { name: 'Creación' }).first().click();
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageUp');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  await page.getByTestId('virtuoso-scroller').press('PageDown');
  const downloadPromise = page.waitForEvent('download');
 // await page.pause();
  await page.getByRole('row', { name: '05-03-26 08:09:00 05-03-26 08' }).locator('a').click();
 // console.log(await page.getByRole('row', { name: '05-03-26 08:09:00 05-03-26 08' }).count());
//  console.log(await page.getByRole('row', { name: '05-03-26 08:09:00 05-03-26 08' }).evaluate(el => el.outerHTML));
  //await page.pause();
  const download = await downloadPromise;
 // await page.pause();
  await page.getByRole('button', { name: 'Carga masiva' }).click();
  await page.getByRole('button', { name: 'Generación de planillas' }).click();
  await page.getByRole('button', { name: 'Carga de Puntos GO' }).click();
  await page.getByRole('button', { name: 'Carga de Puntos GO' }).click();
  
});